# Рекомендательные системы. Матричные разложения

> На этом практическом занятии мы с вами сделаем следующее:
- Обсудим как работает SVD.
- Построим рекомендательную систему на основе метода ALS.
- Сделаем рекомендации пользователям на основании построенной модели.

In [3]:
import pandas as pd
import numpy as np
import random
from sklearn.model_selection import train_test_split


## Load dataset

Мы будем использовать тот же датасет из прошлого урока - MovieLens.

In [4]:
df_ratings = pd.read_csv("ml-latest-small/ratings.csv")
df_movies = pd.read_csv("ml-latest-small/movies.csv")

In [5]:
df_ratings.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [6]:
df_movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

### SVD

In [7]:
from scipy.linalg import svd

In [8]:
# define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]]) #np.nan
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
# SVD
U, s, VT = svd(A) # Factorizes the matrix a into two unitary matrices U and VT, and a 1-D array s of singular values (real, non-negative) such that a == U @ S @ Vh, where S is a suitably shaped matrix of zeros with main diagonal s
print("Unitary matrix having left singular vectors as columns: \n", U) # U*s is the length of projections on the axes (by columns)
print("Singular values: \n", s) # this is diagonal matrix with sigmas on the diagonal (closeness to tthe axes)
print("Unitary matrix having right singular vectors as rows: \n", VT) # ortogonal basis of the projection

Unitary matrix having left singular vectors as columns: 
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Singular values: 
 [9.52551809 0.51430058]
Unitary matrix having right singular vectors as rows: 
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [10]:
m, n = A.shape[0], A.shape[1]

sigma = np.zeros((m, n))
for i in range(min(m, n)):
    sigma[i, i] = s[i]
A_rec = np.dot(np.dot(U,sigma), VT)
print("Reconstructed matrix: \n", A_rec)

Reconstructed matrix: 
 [[1. 2.]
 [3. 4.]
 [5. 6.]]


## Train/Test split

In [11]:
import scipy.sparse as sp
from scipy import sparse
from scipy.sparse.linalg import spsolve

In [12]:
user_item_matrix = df_ratings.pivot_table(index=['userId'], columns=['movieId'], values='rating')
# Contruct a sparse matrix for our users and items containing number of plays
sparse_ui= sp.csr_matrix(user_item_matrix)

In [13]:
sparse_ui.todense()

matrix([[4. , nan, 4. , ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [2.5, 2. , 2. , ..., nan, nan, nan],
        [3. , nan, nan, ..., nan, nan, nan],
        [5. , nan, nan, ..., nan, nan, nan]])

In [14]:
X_train, X_test = train_test_split(sparse_ui, test_size = 0.25, random_state=57)
ind_train, ind_test = train_test_split(user_item_matrix, test_size = 0.25, random_state=57)

In [15]:
X_train.todense()

matrix([[nan, nan, nan, ..., nan, nan, nan],
        [3.5, 4. , nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, 4. , 5. , ..., nan, nan, nan]])

In [16]:
ind_train.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
575         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
323         3.5     4.0     NaN     NaN     NaN     NaN     NaN     NaN   
14          NaN     NaN     NaN     3.0     NaN     NaN     3.0     NaN   
496         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
531         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  9       10      ...  193565  193567  193571  193573  193579  193581  \
userId                   ...                                                   
575         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
323         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
14          NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
496         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
531         NaN     4.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  193583  193585  193587  193609  
userId                                   
575         NaN     NaN     NaN     NaN  
323         NaN     NaN     NaN     NaN  
14          NaN     NaN     NaN     NaN  
496         NaN     NaN     NaN     NaN  
531         NaN     NaN     NaN     NaN  

[5 rows x 9724 columns]

In [17]:
X_res = pd.DataFrame(index=ind_train.index, data=[], columns=['actual'])
for i in X_res.index:
    X_res.loc[i]['actual'] = list(set(ind_train.loc[i][ind_train.loc[i].notnull()].index))

In [18]:
# ind_train.loc[1][ind_train.loc[1].notnull()].index

In [19]:
X_res.head()

actual
userId                                                   
575     [2560, 2436, 2566, 2567, 2568, 2571, 2572, 257...
323     [1, 2, 2571, 1037, 527, 17, 19, 22, 110102, 29...
14      [4, 7, 266, 524, 527, 784, 19, 150, 153, 25, 2...
496     [4993, 111362, 2950, 904, 104841, 912, 84374, ...
531     [4993, 260, 10, 1291, 919, 1961, 2473, 1198, 1...

In [20]:
ind_train_u = pd.Series(ind_train.index.tolist())
ind_train_i = pd.Series(ind_train.columns.values.tolist())

In [21]:
print(X_train.shape, X_test.shape)

(457, 9724) (153, 9724)


In [64]:
ind_train_i.head(5)

0    1
1    2
2    3
3    4
4    5
dtype: int64

### Latent Factor Model ()

Будем искать значение целовой переменной $r_{ui}$ пользователя $u$, поставленная фильму $i$, как скалярное произведение векторов $p_u$ и $q_i$ в некотором пространстве $T$ латентных признаков:
$$
    r_{ui}
    \approx
    \langle p_u, q_i \rangle.
$$


Как мы обсуждали на уроке нам необходимо минимизировать следующий функционал (LFM):

\begin{equation}
\label{eq:lfmReg}
    \sum_{(u, i) \in R}
        \left(
            r_{ui}
            - \langle p_u, q_i \rangle
        \right)^2
    +
    \lambda
    \sum_{u \in U}
        \|p_u\|^2
    +
    \mu
    \sum_{i \in I}
        \|q_i\|^2
    \to
    \min_{P, Q}
\end{equation}

Мы проведем $N$ итераций, в рамках каждой итерации сначала оптимизируем $p$ при фиксированном
$q$, затем $q$ при фиксированном $p$.

Составим матрицу $P$ из векторов $p_u$ и матрицу $Q$ из векторов $q_i$. Матрицей $Q[u] \in R^{n_u×K}$ будем обозначать подматрицу матрицы $Q$ только для товаров, оцененных пользователем $u$, где $n_u$ – количество оценок пользователя $u$.
Шаг перенастройки $p_u$ при фиксированной матрице $Q$ сводится к настройке Ridge-регрессии и выглядит так:
$$A_u = Q[u]^T Q[u] $$
$$d_u = Q[u]^Tr_u $$
$$p_u = (\lambda n_uI + A_u)^{−1}d_u
$$

Есть __явные (explicit)__ предпочтения, которые более надежно дают характеристику подходящего объекта для пользователей:
- Покупки, добавления в корзину
- Рейтинги

И __неявные (implicit)__, их как правило больше:
- Посещение страницы товара
- Просмотр части фильма

__Идея iALS__: предсказываем $s_{ui}$ c весом $c_{ui} = 1 + \alpha*r_{ui}$. Коэффициент $\alpha$ позволяет регулировать влияние явного рейтинга на уверенность в интересе.

\begin{equation}
\label{eq:lfmReg}
    \sum_{(u, i) \in R}
        \left(c_{ui}*(
            s_{ui}
            - \langle p_u, q_i \rangle
        \right)^2)
    +
    \lambda
    \sum_{u \in U}
        \|p_u\|^2
    +
    \mu
    \sum_{i \in I}
        \|q_i\|^2
    \to
    \min_{P, Q}
\end{equation}

In [22]:
from scipy import sparse
from scipy.sparse.linalg import spsolve
# from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MinMaxScaler

In [23]:
seed=57
rstate = np.random.RandomState(seed)
rank_size=10
lambda_val = 0.1
num_user = X_train.shape[0]
num_item = X_train.shape[1]
P = sparse.csr_matrix((rstate.normal(size = (num_user, rank_size)))) # Random numbers in a m x rank shape
Q = sparse.csr_matrix((rstate.normal(size = (num_item, rank_size)))) # Normally this would be rank x n but we can transpose at the end. Makes calculation more simple.
QTQ = Q.T.dot(Q) # QTQ
PTP = P.T.dot(P)
P_eye = sparse.eye(num_user)
Q_eye = sparse.eye(num_item)
lambda_eye = lambda_val * sparse.eye(rank_size) # Our regularization term lambda*I.

In [24]:
u=5
pref = X_train[u, :].toarray() # Grab user row from confidence matrix and convert to dense
pref_u = pref[~np.isnan(pref)] # We take only the movies which the user has rated
u_rated_movies_ind = np.argwhere(~np.isnan(pref))[:,1] # Index of the rated movies
Qu = Q[u_rated_movies_ind, :] # We construct the Qu matrix of only rated existant pairs (u, i)
QuTru = Qu.T.dot(pref_u.T) # This is the QuTPu term
Q[u] = spsolve(QTQ +lambda_eye, QuTru)
print(Q[u].toarray())

[[ 0.0044179  -0.01638758 -0.00766912 -0.00914071  0.02136258 -0.00095192
  -0.00905147  0.01610489  0.00381576 -0.00747813]]


In [36]:
def lfm_als(training_set, lambda_val, iterations=10, rank_size=20, seed=57):
    """
    Model by Bell R.M., Koren Y., Volinsky C. The BellKor 2008 solution to the Netflix Prize.
    
    parameters:
    
    training_set - Our matrix of ratings with shape m x n, where m is the number of users and n is the number of items.
    Should be a sparse csr matrix to save space. 
    
    lambda_val - Used for regularization during alternating least squares. Increasing this value may increase bias
    but decrease variance. Default is 0.1. 
    
    iterations - The number of times to alternate between both user feature vector and item feature vector in
    alternating least squares. More iterations will allow better convergence at the cost of increased computation. 
    The authors found 10 iterations was sufficient, but more may be required to converge. 
    
    rank_size - The number of latent features in the user/item feature vectors. The paper recommends varying this 
    between 20-200. Increasing the number of features may overfit but could reduce bias. 
    
    seed - Set the seed for reproducible results
    
    returns:
    
    The feature vectors for users and items. The dot product of these feature vectors should give you the expected 
    "rating" at each point in your original matrix. 
    """
    
    # Get the size of our original ratings matrix, m x n
    num_user = training_set.shape[0]
    num_item = training_set.shape[1]
    
    # initialize our X/Y feature vectors randomly with a set seed
    rstate = np.random.RandomState(seed)
    
    P = sparse.csr_matrix((rstate.normal(size = (num_user, rank_size)))) # предсставление пользователей
    Q = sparse.csr_matrix((rstate.normal(size = (num_item, rank_size)))) # Normally this would be rank x n but we can transpose at the end. Makes calculation more simple.
    # QTQ = Q.T.dot(Q) # QTQ
    # PTP = P.T.dot(P)
    P_eye = sparse.eye(num_user)
    Q_eye = sparse.eye(num_item)
    lambda_eye = lambda_val * sparse.eye(rank_size) # Our regularization term lambda*I.
    
    # Begin iterations
   
    # Iterate back and forth between solving X given fixed Y and vice versa
    for iter_step in range(iterations):
        # Compute yTy and xTx at beginning of each iteration to save computing time
        QTQ = Q.T.dot(Q) # QTQ
        PTP = P.T.dot(P)
        
        # Being iteration to solve for P based on fixed Q
        for u in range(num_user):
            pref = training_set[u, :].toarray() # Grab user row from confidence matrix and convert to dense
            pref_u = pref[~np.isnan(pref)] # We take only the movies which the user has rated
            u_rated_movies_ind = np.argwhere(~np.isnan(pref))[:,1] # Index of the rated movies
            Qu = Q[u_rated_movies_ind, :] # We construct the Qu matrix of only rated existant pairs (u, i)
            QuTru = Qu.T.dot(pref_u.T) # This is the QuTru term
            Q[u] = spsolve(QTQ +lambda_eye, QuTru) # Solve for Qu = ((QTQ + lambda*I)^-1)QT*Pu | Ax=b
        
        # Begin iteration to solve for Q based on fixed P
        for i in range(num_item):
            pref = training_set[:, i].toarray() # Grab user row from confidence matrix and convert to dense
            pref_i = pref[~np.isnan(pref)]
            i_rated_items_ind = np.argwhere(~np.isnan(pref))[:,0] 
            Pi = P[i_rated_items_ind, :]
            PiTri = Pi.T.dot(pref_i.T) 
            P[u] = spsolve(PTP +lambda_eye, PiTri)     
            
            
    # End iterations
    return P, Q.T

In [37]:
%%time
P, Q = lfm_als(X_train, lambda_val = 0.1, iterations = 10, rank_size = 20)

CPU times: user 7min 1s, sys: 2.04 s, total: 7min 3s
Wall time: 7min 4s


In [38]:
print("P shape: {}".format(P.shape))
print("Q shape: {}".format(Q.shape))

P shape: (457, 20)
Q shape: (20, 9724)


### Find Similar movies

Now that we have the embeddings for all the movies and all the users, we can find similar movies

In [39]:
df_movies[df_movies['title'].str.contains('Shrek')]

movieId                                              title  \
3194     4306                                       Shrek (2001)   
5160     8360                                     Shrek 2 (2004)   
6486    53121                             Shrek the Third (2007)   
6915    64249                             Shrek the Halls (2007)   
7360    78637  Shrek Forever After (a.k.a. Shrek: The Final C...   

                                                 genres  
3194  Adventure|Animation|Children|Comedy|Fantasy|Ro...  
5160  Adventure|Animation|Children|Comedy|Musical|Ro...  
6486        Adventure|Animation|Children|Comedy|Fantasy  
6915                 Adventure|Animation|Comedy|Fantasy  
7360   Adventure|Animation|Children|Comedy|Fantasy|IMAX

In [40]:
# Let's find similar movies to Shrek (2001).
movieId = 5615
ind_i = ind_train_i[ind_train_i == movieId].index[0]

# Get the item row
qi = Q[:, ind_i].toarray()[:, 0]

In [41]:
# Calculate the similarity score between choseen movie and other movies
# and select the top 10 most similar.
scores = Q.T.dot(qi)
top_10 = np.argsort(scores)[::-1][:10]

In [67]:
scores[::-1][:10]

array([ -8.47375052,   2.59539927,  10.46321899, -12.16465916,
        -3.74321442,  -5.09492237,   0.62415503,  -0.9127764 ,
        -7.24430101,  -3.0877332 ])

In [42]:
top_10

array([3977, 6043, 6192, 6991, 5879, 4048, 4439, 7068, 1166, 9547])

In [44]:
# since we have indexes are not equal to movieId, we take the movieId from the 
df_movies[df_movies['movieId']==ind_train_i[5615]]['title'].iloc[0]

'Wind Will Carry Us, The (Bad ma ra khahad bord) (1999)'

In [45]:
movies = []
movies_genres = []
movies_scores = []
movies_ids = []

# Get and print the actual artists names and scores
for idx in top_10:
    movies_ids.append(ind_train_i[idx])
    movies.append(df_movies[df_movies['movieId']==ind_train_i[idx]]['title'].iloc[0])
    movies_genres.append(df_movies[df_movies['movieId']==ind_train_i[idx]]['genres'].iloc[0])
    movies_scores.append(scores[idx])

similar = pd.DataFrame({'movieId': movies_ids, 'movies': movies, 'score': movies_scores, 'genres': movies_genres})
similar

movieId                                             movies      score  \
0     5615                                  Invincible (2001)  29.756241   
1    40723                                  Wolf Creek (2005)  21.278858   
2    45499                       X-Men: The Last Stand (2006)  19.570919   
3    68073                                Pirate Radio (2009)  19.309013   
4    33437                   Unleashed (Danny the Dog) (2005)  18.446562   
5     5772                        My Dinner with André (1981)  18.351032   
6     6564  Lara Croft Tomb Raider: The Cradle of Life (2003)  18.269228   
7    70015                               Polytechnique (2009)  18.228665   
8     1547                                      Shiloh (1997)  17.807164   
9   173873                          Gulliver's Travels (1996)  17.672585   

                                     genres  
0                                     Drama  
1                     Crime|Horror|Thriller  
2                    Action|Sci-Fi|Thriller  
3                              Comedy|Drama  
4               Action|Crime|Drama|Thriller  
5                                     Drama  
6  Action|Adventure|Comedy|Romance|Thriller  
7                               Crime|Drama  
8                            Children|Drama  
9                Adventure|Children|Fantasy

### Recommend movies to the user

Let's write a function to predict for every user a movie not watched.

In [57]:
def predict_top_k(user_id, training_set, P, Q, df_movies, ind_train_i, k=10):
    """
    Recommend items for a given user given a trained model
    Args:
        user_id (int): The id of the user we want to create recommendations for.
        data_sparse (csr_matrix): Our original training data.
        P (csr_matrix): Users embedding
        Q (pandas.DataFrame): Item embedding
        k (int): How many recommendations we want to return:
    Returns:
        recommendations (pandas.DataFrame): DataFrame with k movies and scores
    """
  
    # Get all interactions by the user
    user_interactions = training_set[user_id,:].toarray()

    # We don't want to recommend items the user has consumed. So let's
    # set them all to 0 and the NaNs to 1.
    
    user_interactions = np.where(~np.isnan(user_interactions), 0, user_interactions)
    user_interactions = np.nan_to_num(user_interactions[0], nan=1)

    # This is where we calculate the recommendation by taking the 
    # dot-product of the user vectors with the item vectors.
            
    rec_vector = P[user_id,:].dot(Q).toarray()

    # Let's scale our scores between 0 and 1 to make it all easier to interpret.
    min_max = MinMaxScaler()
    rec_vector_scaled = min_max.fit_transform(rec_vector.reshape(-1,1))[:,0]
    recommend_vector = user_interactions*rec_vector_scaled
   
    # Get all the movies indices in order of recommendations (descending) and
    # select only the top "k" items.
    item_idx = np.argsort(recommend_vector)[::-1][:k]

    # Loop through our recommended movie indicies and look up the movie title
    movies = []
    movies_scores = []
    movies_ids = []

    # Get and print the actual movie names, IDs and scores
    for idx in item_idx:
        movies_ids.append(ind_train_i[idx])
        movies.append(df_movies[df_movies['movieId']==ind_train_i[idx]]['title'].iloc[0])
        movies_scores.append(recommend_vector[idx])

    similar = pd.DataFrame({'movieId': movies_ids, 'title': movies, 'score': movies_scores})
    
    return similar

In [58]:
# Let's generate and print our recommendations
user_id = 103
recommendations = predict_top_k(user_id, X_train, P, Q, df_movies, ind_train_i, k=10)
print(recommendations)

   movieId                                              title     score
0     5615                                  Invincible (2001)  1.000000
1    93502                                  Ledge, The (2011)  0.994485
2    89072                                  Stake Land (2010)  0.957493
3     4334                                       Yi Yi (2000)  0.947172
4     5570                              Thesis (Tesis) (1996)  0.934872
5    26236  White Sun of the Desert, The (Beloe solntse pu...  0.932483
6    80549                                      Easy A (2010)  0.931932
7     4395  Big Deal on Madonna Street (I Soliti Ignoti) (...  0.926718
8   144222                             Bros Before Hos (2013)  0.924318
9     3790                                      Groove (2000)  0.922260


In [56]:
user_interactions = X_train[103,:].toarray()
user_interactions = np.where(~np.isnan(user_interactions), 0, user_interactions)
user_interactions = np.nan_to_num(user_interactions[0], nan=1)

user_interactions

array([1., 1., 1., ..., 1., 1., 1.])

In [60]:
# Let's put it in a list of recommendation for every user
pred = []
for i in X_res.index:
    ind = ind_train_u[ind_train_u == i].index[0] # get index in the sparse matrix
    recom = predict_top_k(ind, X_train, P, Q, df_movies, ind_train_i, k=10)
    pred.append(recom['movieId'].to_list())

In [61]:
X_res['predicted'] = pred

In [62]:
X_res.head()

actual  \
userId                                                      
575     [2560, 2436, 2566, 2567, 2568, 2571, 2572, 257...   
323     [1, 2, 2571, 1037, 527, 17, 19, 22, 110102, 29...   
14      [4, 7, 266, 524, 527, 784, 19, 150, 153, 25, 2...   
496     [4993, 111362, 2950, 904, 104841, 912, 84374, ...   
531     [4993, 260, 10, 1291, 919, 1961, 2473, 1198, 1...   

                                                predicted  
userId                                                     
575     [85025, 168250, 76060, 3758, 5991, 3790, 91542...  
323     [103483, 32314, 6660, 8383, 81535, 37739, 2278...  
14      [4403, 56941, 4022, 157172, 104074, 2028, 1350...  
496     [47538, 78160, 994, 72171, 64695, 4973, 3317, ...  
531     [6516, 4397, 567, 68952, 4293, 3719, 5247, 418...